server:
  port: 8081 # 端口
  servlet:
    context-path: /parking

spring:
  application:
    name: parking  # 应用名

  datasource:
    # dynamic-datasource-spring-boot-starter 动态数据源的配配项，对应 DynamicDataSourceProperties 类
    dynamic:
      primary: all-ds # 设置默认的数据源或者数据源组，默认值即为 master
      datasource:
        # 系统总数据源配置
        all-ds:
          url: jdbc:mysql://127.0.0.1:3306/parking_lot?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: Qwer;t592665
        # 系统支数据源 swpu配置
        swpu-ds:
          url: jdbc:mysql://127.0.0.1:3306/parking_lot_swpu?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: Qwer;t592665
      seata: true # 是否启动对 Seata的集成

# Seata 配置项，对应 SeataProperties类
seata:
  application-id: ${spring.application.name} # Seata 应用编号，默认为 ${spring.application.name}
  tx-service-group: ${spring.application.name}-group # Seata 事务组编号，用于 TC 集群名
  # 服务配置项，对应 ServiceProperties 类
  service:
    # 虚拟组和分组的映射
    vgroup-mapping:
      parking-group: default
    # 分组和 Seata 服务的映射
    grouplist:
      default: 127.0.0.1:8091
